version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    container_name: 'django_rest'
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_rest
    # ポートが被る場合、手前のポート番号を変更する
    ports:
      - "8004:8000"
    depends_on:
      - db
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8001:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: test@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
volumes:
  postgres_data:
  pgadmin4_data: